### PR TITLE
update welcome page

### PR DESCRIPTION
**Pull request by Amutha37**
Please review this welcome page updated according to new design.

### CODE REVIEW

**Comment by hqtan** [comment]
Thx for your PR @Amutha37 :bow: 

Nice work! :raised_hands: 

A couple of suggestions:
- can we stick to using double-quotes (") for strings please rather than single quotes (')? We use double quotes everywhere else in the codebase, so let's keep that consistent. I suspect that it is your IDE's lint settings that is making the changes for you. You may want to update your lint settings for this project
- In your PR description, can you link the trello card's url to this PR?

Your PR should be ready to merge once the above points have been addressed :+1: 
@batteries76 , @ymloh , any suggestions?

**Comment by hqtan** [comment]
[DEV: update welcome page](https://trello.com/c/UJMBoS1t/284-dev-update-welcome-page)

**Comment by amu3** [comment]
Thank you for the highlights. I have to reinstall and change all my sett In
VSCode. I just reinstalled my VSCode that must be the cause. I will get
that settings done today.

Amutha

**Comment by Amutha37** [comment]
Hi Qing, You can review the quotation mark I have update to double quote now. 

Trello card  :  https://trello.com/c/UJMBoS1t/284-dev-update-welcome-page

**Review by hqtan — APPROVED** [review]
lgtm

**Pull request merged**
