### PR TITLE
link to `form/workArrangement` for 'Start' button

### PR DESCRIPTION
**Pull request by hqtan**
this PR relates to the [task for 'Work Arrangement' page](https://trello.com/c/uMT9o9s9), implemented in #72 

Depends on #72 

## What
this PR updates link in the Welcome Page's 'Start' button to take user to the `WorkArrangement` page, the first question in the updated Survey flow (see latest [figma design here](https://www.figma.com/file/Y42AKuHDW46LiLDaTOs6sM/Heroes-carbon-calculator-designs?node-id=978%3A55067) 

## Acceptance Criteria
clicking on the 'Start' button on the [Welcome page](https://github.com/CodeforAustralia/council-emissions-calculator/blob/main/pages/index.js) should lead to the [`WorkArrangement` page](.pages/form/WorkArrangement.jsx), once #72 has been merged into `main` branch

### CODE REVIEW

**Comment by hqtan** [comment]
[DEV: Work Arrangement Page](https://trello.com/c/uMT9o9s9/301-dev-work-arrangement-page)

**Comment by OlaShabalina** [comment]
Looks straight-forward @hqtan 👍

**Comment by Amutha37** [comment]
Look good, changing one line which take the welcome page to workArangementPage.

**Comment by hqtan** [comment]
Thx for the review @OlaShabalina , @Amutha37 :bow: 
can one of you approve this PR, so that it can be merged? :pray:

**Comment by Amutha37** [comment]
> Thx for the review @OlaShabalina , @Amutha37 🙇 can one of you approve this PR, so that it can be merged? 🙏

My membership hasn't change. After change I can do that.

**Review by OlaShabalina — APPROVED** [review]

**Comment by OlaShabalina** [comment]
Approved @hqtan 👍

**Comment by Amutha37** [comment]
This PR as all passed its review with no conflict.

**Pull request merged**
