### PR TITLE
Added  svg images for the buttons, cloud and progress dots bar.

### PR DESCRIPTION
**Pull request by Amutha37**
Added svg images for the buttons, cloud and progress bar needed for… travelMethod page.
Folders the changes will take place :
1.public/Images/clouds
2.public/Images/transportmode-icons
3.public/Images/progress-bar
4. added the svg object in utils/constants.js

### CODE REVIEW

**Comment by Amutha37** [comment]
trello card for this task : https://trello.com/c/z50v3GrA/297-dev-travel-method-selection-page

**Comment by hqtan** [comment]
The svg images looks good to me @Amutha37 :+1:
Happy to merge this PR if no further changes are needed

**Comment by amu3** [comment]
Yes you can .👍

**Review by hqtan — APPROVED** [review]
lgtm

**Pull request merged**
