### PR TITLE
Update results pdf with copy of 1st revision

### PR DESCRIPTION
**Pull request by hqtan**
## Overview of the Pull Request:
This PR updates the results pdf with the copy of 1st revision.
1st revision contains minor changes, including changes to text in 'Staff Suggestions' section of results page.

## How Has This Been Tested?
download pdf file from preview deployment, and verify that pdf content is the same as `public/202207_results/council_survey_results_20220818_rev1.pdf`

## Pull Request Checklist:

Make sure the following checkboxes`[ ]` are checked with `x` before sending your PR -- thank you!

- [x] Is your pull request up-to-date with `main` branch?
- [x] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?
- [x] Have you written instructions on how to test that your changes work as expected?
- [x] Have you tested your work thoroughly on your local machine to ensure you are not breaking anything?

### CODE REVIEW

**Comment by RCode-Blue** [comment]
Just wondering if it would be better to keep the value and the unit together

image

**Comment by RCode-Blue** [comment]
Maybe have a space between vs. and active

image

**Comment by hqtan** [comment]
Hi @RCode-Blue 👋🏽 
Thanks for pointing that out!
I'll bring this to Sean's attention tomorrow morning to get his assistance to update pdf 👍🏽

**Review by OlaShabalina — APPROVED** [review]
Well done @hqtan !

**Pull request merged**
