### PR TITLE
How we calculate

### PR DESCRIPTION
**Pull request by OlaShabalina**
## Overview of the Pull Request:

Formula block update:

* Replace Image with text and formulas:
  * formulas as svg components;
  * sigma as a Chakra UI icon;
  * explanation as text;
* Left aligned as per new figma update;

Out of scope:
* Alt text for formulas - requested from the team on Figma & Slack, need help from somebody who did math in Australia (feel free to do that guys 😄);
* Responsiveness;

image

## How Has This Been Tested?
This is a visual change, N/A

## Pull Request Checklist:

Make sure the following checkboxes`[ ]` are checked with `x` before sending your PR -- thank you!

~- [ ] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?~
- [x] Is your pull request up-to-date with `main` branch?
- [x] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?
- [x] Have you written instructions on how to test that your changes work as expected?
- [x] Have you tested your work thoroughly on your local machine to ensure you are not breaking anything?

### CODE REVIEW

**Comment by hqtan** [comment]
Nice work on the calculation text @OlaShabalina ! 🙌🏽 

There's a typo on the svg filename:
- `formula-2.svg` should be renamed to `formula-3.svg`
- `formula-3.svg` should be renamed to `formula-2.svg`

I think once the files have been renamed, the correct formulas will appear in the right position on the page (above the explanations for their variable names).

The last parentheses in this formula looks cropped off as well - do we have another svg that includes the final parentheses in formula?
image

**Comment by hqtan** [comment]
I've made a couple of suggestions in the Figma board to improve the understanding of calculations, by:
- [moving the bold text at the bottom of Calculation formula block (see screenshot) to between the between the '+' sign and the 'Σ(qxf)' formula](https://www.figma.com/file/opEaLsTMNJjhKHx3KNXRe6?node-id=2585:41502#239618425)
image

- [increasing the prominence of the '+' sign](https://www.figma.com/file/opEaLsTMNJjhKHx3KNXRe6?node-id=2585:41502#239619012)

we can probably address these suggestions in a separate PR 👍🏽

**Comment by OlaShabalina** [comment]
> Nice work on the calculation text @OlaShabalina ! 🙌🏽
> 
> There's a typo on the svg filename:
> 
> * `formula-2.svg` should be renamed to `formula-3.svg`
> * `formula-3.svg` should be renamed to `formula-2.svg`
> 
> I think once the files have been renamed, the correct formulas will appear in the right position on the page (above the explanations for their variable names).
> 
> The last parentheses in this formula looks cropped off as well - do we have another svg that includes the final parentheses in formula? image

Fixed, that's exactly what happened with the names ))

**Review by hqtan — APPROVED** [review]
nice work @OlaShabalina !
🙇🏽

**Pull request merged**
