### PR TITLE
Progress bar

### PR DESCRIPTION
**Pull request by OlaShabalina**
## Overview of the Pull Request:
update progress bar for WorkOnSiteDays.jsx, WorkFromHomeDays.jsx, TravelDays.jsx

## link to Trello card or Github issue
image

## How Has This Been Tested?
N/A

## Pull Request Checklist:

Make sure the following checkboxes`[ ]` are checked with `x` before sending your PR -- thank you!

- [x] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?
- [x] Is your pull request up-to-date with `main` branch?
- [x] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?
- [x] Have you written instructions on how to test that your changes work as expected?
- [x] Have you tested your work thoroughly on your local machine to ensure you are not breaking anything?

### CODE REVIEW

**Comment by hqtan** [comment]
Hi @OlaShabalina,

with regards to `WorkOnSiteDays` page, its progress bar can change depending on selected work arrangement.
When work arrangement is:
  - `onsite`: progress bar should display 2 dots
  - `hybrid`: progress bar should display 3 dots

To cater for that change, I added to this PR a `getProgressBar()` method to decide which progress bar to  display.

Can you review it, and lemme know what you think? 
If that's not what you had in mind, I'm happy to remove my changes :bow:

**Comment by OlaShabalina** [comment]
Good call @hqtan, looks good! 
Although, it also means we have to change all the next pages as well and increate the progress bar length for hybrid mode...

**Comment by hqtan** [comment]
Hi @OlaShabalina ,
Yes, that right. We'd have to update each page that comes after `WorkFromHomeDays` page to put in conditional checks for progress bar!

Seems like a fair bit more work to factor in an extra 'dot' :sweat:

Let's leave it for now. We can address it in another PR if need be. What we have in this PR works for now :+1:

**Review by hqtan — APPROVED** [review]
Good work @OlaShabalina !
Thx for your efforts :bow:

**Pull request merged**
