### PR TITLE
Trip count and travel methods

### PR DESCRIPTION
**Pull request by RCode-Blue**
## Overview of the Pull Request:
- Refactored fake data to come from `2022-results.json` file
- Edited layout to charts will fit properly into smaller screen sizes
- Edited layout so that the alignment is to the left

## How Has This Been Tested?
When implemented, the layout of the component should appear as below:

image

image

## Pull Request Checklist:

Make sure the following checkboxes`[ ]` are checked with `x` before sending your PR -- thank you!

- [ ] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?
- [x] Is your pull request up-to-date with `main` branch?
- [x] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?
- [x] Have you written instructions on how to test that your changes work as expected?
- [x] Have you tested your work thoroughly on your local machine to ensure you are not breaking anything?

### CODE REVIEW

**Comment by hqtan** [comment]
Hi @RCode-Blue,

It looks awesome in desktop view 😍 

In mobile view though, this section is cropped off on the left (see screenshot):
image

Was it your intention to address that in this PR, or another PR?

**Comment by RCode-Blue** [comment]
Yes

**Comment by RCode-Blue** [comment]
I'm working on the overall page layout now, which will address the Pie Charts layout. This will be submitted in another PR.

**Review by hqtan — APPROVED** [review]
lgtm 🙌🏽

**Pull request merged**
