### PR TITLE
Adding pull request template

### PR DESCRIPTION
**Pull request by hqtan**
## Overview of the Pull Request:
Creating a Pull Request template to make sure that a there's standard process for every pull request and to have a to-do list for the author to check before requesting a review.

## link to Trello card or Github issue
addresses #90

## How Has This Been Tested?
This change can only be tested once it has been merged to `main` branch.
When a PR author creates a new PR, author should see the PR description pre-filled with this template.

## Pull Request Checklist:

Make sure the following checkboxes`[ ]` are checked with `x` before sending your PR -- thank you!

- [x] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?
- [x] Is your pull request up-to-date with `main` branch?
- [ ] ~Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?~
- [x] Have you written instructions on how to test that your changes work as expected?
- [ ] ~Have you tested your work thoroughly on your local machine to ensure you are not breaking anything?~

### CODE REVIEW

**Review by OlaShabalina — APPROVED** [review]

**Comment by OlaShabalina** [comment]
Great idea @hqtan to have a template for PRs !

**Review by Amutha37 — COMMENTED** [review]
Nice check list. Will this go into Read me for now?

**Comment by hqtan** [comment]
Hi @Amutha37 ,

> Nice check list. Will this go into Read me for now?

When you create a new Pull Request against this repo, you should see the description of your new pull request populated with the contents of the template in this PR.

The idea of this template is to provide PR authors with a checklist and some guidelines on the minimum bits of details that they should provide in each new PR, to ensure all the useful info needed for reviewing PRs are already there. :+1:

**Comment by Amutha37** [comment]
Thats sound very useful for long term habits.

**Pull request merged**
